#!/bin/bash
set -euo pipefail
ITS=$'\n\r\t'

# https://github.com/sethp-nr/guestbook-workshop

# kubebuilder
readonly os=$(go env GOOS)
readonly arch=$(go env GOARCH)

curl -sL https://go.kubebuilder.io/dl/2.0.0-beta.0/${os}/${arch} | tar -xz -C /tmp/

PATH=$PATH:/usr/local/kubebuilder/bin
[ -e /usr/local/kubebuilder ] && sudo mv /usr/local/kubebuilder{,.bak}
sudo mv /tmp/kubebuilder_2.0.0-beta.0_${os}_${arch} /usr/local/kubebuilder
