#!/bin/bash
set -euo pipefail
ITS=$'\n\r\t'

k3d ls 2>/dev/null | grep -q 'wiki' || {
  k3d create \
      --server-arg --tls-san="127.0.0.1" \
      --publish 80:80 \
      -v "$HOME/.wiki-k8s:/macos/.wiki-k8s" \
      -v "$HOME/workspace/fedwiki:/macos/fedwiki" \
      --name wiki
}

readonly CONFIG=$HOME/.zshrc.d/kubeconfig
[ -f $CONFIG ] && grep -q wiki $CONFIG || {
    for retries in 1 2 3 4 5 6 7 8; do
      if k3d get-kubeconfig --name=wiki &>/dev/null; then
        break
      fi
      echo waiting for cluster config: $retries of 8 tries
      sleep 1
    done
    cat > $CONFIG <<EOF
#!/bin/bash
export KUBECONFIG="$(k3d get-kubeconfig --name=wiki)"
EOF
}
