#!/bin/bash
set -euo pipefail
ITS=$'\n\r\t'

readonly VERSION=0.40.0
command -v deno > /dev/null \
  && deno -V | egrep -q "^deno $VERSION\$" || {
  export DENO_INSTALL=/usr/local
  curl -fsSL https://deno.land/x/install/install.sh | sh -s "v${VERSION}"
}
